### ISSUE TITLE
Optional Parameters Unsupported

### ISSUE THREAD

**Issue by kloetzl** [common-workflow-language/cwl2argparse#12]
The [CWL spec](http://www.commonwl.org/v1.0/CommandLineTool.html#Document_preprocessing) allows to define optional parameters by simply adding a `?` to a type. For example see [inp.cwl](http://www.commonwl.org/v1.0/UserGuide.html#Essential_input_parameters) from the User Guide. cwl2argparse fails with error message `KeyError: 'File?'` in this case.

**Comment by anton-khodak** [comment]
@kloetzl you're right, this is v1.0 feature which `cwl2argparse` doesn't support at the moment. I will fix it ASAP

**Comment by kloetzl** [comment]
Great! ☺
